version: "3.7"

services:

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: tap_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin4321
      MYSQL_ROOT_PASSWORD: admin4321
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  fastapi:
    build: .
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - 8080:8080
    volumes:
      - ./src:/code
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=tap_db
      - DB_USER=admin
      - DB_PASSWORD=admin4321

volumes:
  db_data:


  